# Pull Geth into a second stage deploy alpine container
FROM ubuntu:latest

COPY ./build/bin/geth /usr/local/bin/
COPY ./genesis/docker-entrypoint.sh /usr/local/bin/
COPY ./genesis/genesis.json /genesis/ 
VOLUME /genesis/
VOLUME /data/
WORKDIR /data/

EXPOSE 8545 8546 8547 30303 30303/udp
ENTRYPOINT ["docker-entrypoint.sh"]
